import {
  Books,
  Briefcase,
  House,
  Star,
  Airplane,
  Coffee,
  MoneyWavy,
  MusicNotes,
  ShoppingBag,
  Calendar,
  CheckSquare,
  Heart,
  Globe,
  PencilSimple,
  Wrench,
  UserCircle,
} from "@phosphor-icons/react"

export const iconMap: Record<string, React.ElementType> = {
  "study-icon": Books,
  "work-icon": Briefcase,
  "personal-icon": House,
  "favorite-icon": Star,
  "travel-icon": Airplane,
  "shopping-icon": ShoppingBag,
  "finance-icon": MoneyWavy,
  "relax-icon": Coffee,
  "event-icon": Calendar,
  "hobby-icon": MusicNotes,
  "task-icon": CheckSquare,
  "health-icon": Heart,
  "home-icon": House,
  "world-icon": Globe,
  "default-icon": PencilSimple,
  "maintenance-icon": Wrench,
  "profile-icon": UserCircle,
};
